@echo off
setlocal enabledelayedexpansion
REM Builds reshadefx_cli.exe, reshadefx_stats.exe, and reshadefx_rga.exe from
REM crosire/reshade's real, unmodified compiler source, using MinGW-w64.
REM
REM Requires: git, and a MinGW-w64 g++ (x86_64) on PATH.
REM   Easiest install: https://winlibs.com (download, unzip, add its bin\ to PATH)
REM   or via MSYS2: pacman -S mingw-w64-x86_64-gcc
REM
REM Usage: build_reshadefx_tools.bat [output_dir]

set "RESHADE_COMMIT=358c345ca2fe64f86e67c694f8379c356627adcb"
set "SCRIPT_DIR=%~dp0"
if exist "%SCRIPT_DIR%RESHADE_VERSION" (
	set /p RESHADE_COMMIT=<"%SCRIPT_DIR%RESHADE_VERSION"
)
set "OUT_DIR=%~1"
if "%OUT_DIR%"=="" set "OUT_DIR=%SCRIPT_DIR%bin"
set "WORK_DIR=%TEMP%\reshadefx_build_%RANDOM%"

where g++ >nul 2>nul
if errorlevel 1 (
	echo ERROR: g++ not found on PATH. Install MinGW-w64 ^(e.g. from winlibs.com^) first.
	exit /b 1
)
where git >nul 2>nul
if errorlevel 1 (
	echo ERROR: git not found on PATH.
	exit /b 1
)

echo Fetching reshade @ %RESHADE_COMMIT% ...
git clone --quiet https://github.com/crosire/reshade.git "%WORK_DIR%\reshade"
if errorlevel 1 exit /b 1
pushd "%WORK_DIR%\reshade"
git checkout --quiet %RESHADE_COMMIT%
if errorlevel 1 exit /b 1
popd

echo Fetching SPIR-V headers ...
git clone --quiet --depth 1 https://github.com/KhronosGroup/SPIRV-Headers.git "%WORK_DIR%\reshade\deps\spirv"
if errorlevel 1 exit /b 1

REM Parse "vMAJOR.MINOR.REV" from RESHADE_COMMIT for --version text; falls
REM back to 0.0.0 if it's a raw commit hash instead (no dots to split on).
set "VERSTR=%RESHADE_COMMIT%"
if "%VERSTR:~0,1%"=="v" set "VERSTR=%VERSTR:~1%"
set "VER_MAJOR="
set "VER_MINOR="
set "VER_REV="
for /f "tokens=1,2,3 delims=." %%a in ("%VERSTR%") do (
	set "VER_MAJOR=%%a"
	set "VER_MINOR=%%b"
	set "VER_REV=%%c"
)
if "%VER_MINOR%"=="" set "VER_MAJOR=0"
if "%VER_MINOR%"=="" set "VER_REV=0"
if "%VER_MINOR%"=="" set "VER_MINOR=0"

REM res/version.h is normally generated by the Visual Studio build; only
REM used here for --version text and a preprocessor macro.
if not exist "%WORK_DIR%\reshade\res" mkdir "%WORK_DIR%\reshade\res"
set "VH=%WORK_DIR%\reshade\res\version.h"
echo #pragma once > "%VH%"
echo #define VERSION_MAJOR %VER_MAJOR% >> "%VH%"
echo #define VERSION_MINOR %VER_MINOR% >> "%VH%"
echo #define VERSION_REVISION %VER_REV% >> "%VH%"
echo #define VERSION_STRING_PRODUCT "ReShade %VER_MAJOR%.%VER_MINOR%.%VER_REV% (mingw-built reshadefx tools)" >> "%VH%"

REM Stub out the DXBC backend so the CLI tool still links; --dxbc simply is
REM not available in this build (it needs Microsoft's D3DCompiler, and isn't
REM needed to validate a shader - HLSL/GLSL/SPIR-V codegen already proves it).
set "DS=%WORK_DIR%\dxbc_stub.cpp"
echo #include "effect_codegen.hpp" > "%DS%"
echo reshadefx::codegen *reshadefx::create_codegen_dxbc(unsigned int, bool, bool, int) >> "%DS%"
echo { >> "%DS%"
echo 	return nullptr; >> "%DS%"
echo } >> "%DS%"

if not exist "%OUT_DIR%" mkdir "%OUT_DIR%"
for %%I in ("%OUT_DIR%") do set "OUT_DIR=%%~fI"
REM ^ resolve to an absolute path now, before pushd changes the working directory
pushd "%WORK_DIR%\reshade"

set "INCLUDES=-I source -I res -I deps\spirv\include\spirv\unified1"
set "COMMON_SRC=source\effect_lexer.cpp source\effect_preprocessor.cpp source\effect_parser_exp.cpp source\effect_parser_stmt.cpp source\effect_symbol_table.cpp source\effect_expression.cpp"

REM share.h provides SH_DENYWR, which MSVC headers define but MinGW's
REM equivalent lives in a separate header the source doesn't include.
echo Building reshadefx_cli.exe ...
g++ -std=c++17 -O2 -static -include share.h %INCLUDES% ^
	%COMMON_SRC% source\effect_codegen_hlsl.cpp source\effect_codegen_glsl.cpp source\effect_codegen_spirv.cpp ^
	tools\fxc.cpp "%WORK_DIR%\dxbc_stub.cpp" ^
	-o "%OUT_DIR%\reshadefx_cli.exe"
if errorlevel 1 exit /b 1

echo Building reshadefx_stats.exe ...
g++ -std=c++17 -O2 -static -include share.h %INCLUDES% ^
	%COMMON_SRC% source\effect_codegen_spirv.cpp ^
	"%SCRIPT_DIR%reshadefx_stats.cpp" ^
	-o "%OUT_DIR%\reshadefx_stats.exe"
if errorlevel 1 exit /b 1

echo Building reshadefx_rga.exe ...
g++ -std=c++17 -O2 -static -include share.h %INCLUDES% ^
	%COMMON_SRC% source\effect_codegen_spirv.cpp ^
	"%SCRIPT_DIR%reshadefx_rga.cpp" ^
	-o "%OUT_DIR%\reshadefx_rga.exe"
if errorlevel 1 exit /b 1

popd
rmdir /s /q "%WORK_DIR%"

echo Done. Binaries in %OUT_DIR%
echo Example: %OUT_DIR%\reshadefx_cli.exe --hlsl -I path\to\reshade-shaders\Shaders -Fo out.hlsl myshader.fx
echo Example: %OUT_DIR%\reshadefx_stats.exe -I path\to\reshade-shaders\Shaders myshader.fx
echo Example: %OUT_DIR%\reshadefx_rga.exe -I path\to\reshade-shaders\Shaders --rga path\to\rga.exe --asic gfx1100 myshader.fx
