#!/usr/bin/env bash
# ReShade Testing Initiative - Linux/macOS build.
#
# Builds the tools from crosire/reshade's own compiler source, pinned to the
# tag in RESHADE_VERSION:
#
#   reshadefx_cli        crosire's tools/fxc.cpp, unmodified. Equivalent to the
#                        ReShadeFXC that ships with ReShade. No --dxbc here
#                        (upstream's DXBC backend needs Windows' D3DCompiler).
#   reshadefx_cli_fixed  the same, with tools/fxc-fix.py applied (six fixes, see
#                        docs/upstream/reshade-fxc.md) and a working --dxbc on
#                        top of vkd3d-shader.
#   reshadefx_rga        per-stage SPIR-V instruction cost, optional RGA driver.
#   fxstat               SPIR-V + DXBC instruction statistics, baseline/diff.
#   reshadefx_coverage   how much of a shader corpus the vkd3d DXBC path compiles.
#
# usage: ./build_reshade_testing_initiative.sh [output_dir] [--cli] [--cli-fixed]
#                                              [--rga] [--fxstat] [--coverage]
#
# No tool flags = build all of them. Output defaults to ./bin.
#
# Needs: git, g++, python3. Also, depending on what is built:
#   SPIRV-Tools        fxstat (required), reshadefx_rga --optimize (optional)
#                      Debian/Ubuntu: apt-get install spirv-tools
#   bison, flex        vkd3d-shader, for reshadefx_cli_fixed / fxstat / coverage
#   cmake              fxstat
#
# Downloaded dependencies are cached in ./.deps (gitignored; override with
# DEPS_DIR). Delete it to force a clean fetch.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
RESHADE_REF="$(tr -d '[:space:]' < "$SCRIPT_DIR/RESHADE_VERSION")"
DEPS_DIR="${DEPS_DIR:-$SCRIPT_DIR/.deps}"

OUT_DIR=""
WANT_CLI=0 WANT_CLI_FIXED=0 WANT_RGA=0 WANT_FXSTAT=0 WANT_COVERAGE=0
ANY_SELECTED=0
while [ $# -gt 0 ]; do
	case "$1" in
		--cli)       WANT_CLI=1;       ANY_SELECTED=1 ;;
		--cli-fixed) WANT_CLI_FIXED=1; ANY_SELECTED=1 ;;
		--rga)       WANT_RGA=1;       ANY_SELECTED=1 ;;
		--fxstat)    WANT_FXSTAT=1;    ANY_SELECTED=1 ;;
		--coverage)  WANT_COVERAGE=1;  ANY_SELECTED=1 ;;
		-h|--help)   sed -n '2,30p' "$0"; exit 0 ;;
		-*)          echo "unknown option: $1" >&2; exit 1 ;;
		*)           OUT_DIR="$1" ;;
	esac
	shift
done
if [ "$ANY_SELECTED" -eq 0 ]; then
	WANT_CLI=1 WANT_CLI_FIXED=1 WANT_RGA=1 WANT_FXSTAT=1 WANT_COVERAGE=1
fi
NEED_VKD3D=$(( WANT_CLI_FIXED | WANT_COVERAGE | WANT_FXSTAT ))

OUT_DIR="${OUT_DIR:-$SCRIPT_DIR/bin}"
mkdir -p "$OUT_DIR" "$DEPS_DIR"
OUT_DIR="$(cd "$OUT_DIR" && pwd)"

# --- checks -----------------------------------------------------------------

HAVE_SPIRV_TOOLS=0
if [ -f /usr/include/spirv-tools/optimizer.hpp ] || [ -n "${SPIRV_TOOLS_INCLUDE_DIR:-}" ]; then
	HAVE_SPIRV_TOOLS=1
fi
if [ "$WANT_FXSTAT" -eq 1 ] && [ "$HAVE_SPIRV_TOOLS" -eq 0 ]; then
	echo "ERROR: fxstat needs SPIRV-Tools (Debian/Ubuntu: apt-get install spirv-tools)." >&2
	echo "       To build without it, pick tools explicitly, e.g. --cli --cli-fixed --rga --coverage" >&2
	exit 1
fi
if [ "$WANT_FXSTAT" -eq 1 ]; then
	command -v cmake >/dev/null || { echo "ERROR: fxstat needs cmake." >&2; exit 1; }
fi

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

# --- reshade + SPIR-V headers, pinned ---------------------------------------

R="$DEPS_DIR/reshade-$RESHADE_REF"
if [ ! -f "$R/source/effect_parser.hpp" ]; then
	echo "Fetching reshade $RESHADE_REF ..."
	rm -rf "$R"
	git -c advice.detachedHead=false clone --quiet --depth 1 --branch "$RESHADE_REF" https://github.com/crosire/reshade.git "$R"
fi
# Local patches to the reshade checkout (patches/*.patch), applied once.
for P in "$SCRIPT_DIR"/patches/*.patch; do
	[ -f "$P" ] || continue
	if ! git -C "$R" apply --reverse --check "$P" 2>/dev/null; then
		echo "Applying $(basename "$P") ..."
		git -C "$R" apply "$P"
	fi
done
if [ ! -f "$R/deps/spirv/include/spirv/unified1/spirv.hpp" ]; then
	echo "Fetching SPIR-V headers (the commit reshade $RESHADE_REF pins) ..."
	git -C "$R" submodule update --quiet --init --depth 1 deps/spirv
fi

# res/version.h is generated by the Visual Studio build; used for --version
# text and the __RESHADE__ macro. Written to the work dir, not the checkout.
VER_NUMS="$(echo "$RESHADE_REF" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' || echo "0.0.0")"
VER_MAJOR="$(echo "$VER_NUMS" | cut -d. -f1)"
VER_MINOR="$(echo "$VER_NUMS" | cut -d. -f2)"
VER_REV="$(echo "$VER_NUMS" | cut -d. -f3)"
VER_NUM=$((10#$VER_MAJOR * 10000 + 10#$VER_MINOR * 100 + 10#$VER_REV))
mkdir -p "$WORK_DIR/res"
cat > "$WORK_DIR/res/version.h" << EOF
#pragma once
#define VERSION_MAJOR $VER_MAJOR
#define VERSION_MINOR $VER_MINOR
#define VERSION_REVISION $VER_REV
#define VERSION_STRING_PRODUCT "ReShade $VER_MAJOR.$VER_MINOR.$VER_REV (ReShade Testing Initiative build)"
EOF

# --- vkd3d-shader (only for the tools that need --dxbc on Linux) -------------

VKD3D="$DEPS_DIR/vkd3d"
if [ "$NEED_VKD3D" -eq 1 ] && [ ! -f "$VKD3D/libvkd3d-shader.a" ]; then
	bash "$SCRIPT_DIR/tools/build-vkd3d-shader.sh" "$VKD3D"
fi

# --- shared compile settings -----------------------------------------------

FX_SRC=(
	"$R/source/effect_lexer.cpp"
	"$R/source/effect_preprocessor.cpp"
	"$R/source/effect_parser_exp.cpp"
	"$R/source/effect_parser_stmt.cpp"
	"$R/source/effect_symbol_table.cpp"
	"$R/source/effect_expression.cpp"
)
CODEGEN_SRC=(
	"$R/source/effect_codegen_hlsl.cpp"
	"$R/source/effect_codegen_glsl.cpp"
	"$R/source/effect_codegen_spirv.cpp"
)
INCLUDES=(-I "$R/source" -I "$WORK_DIR/res" -I "$R/deps/spirv/include/spirv/unified1")
VKD3D_INCLUDES=(-I "$VKD3D/wine-src/libs/vkd3d/include" -I "$VKD3D/shim")
VKD3D_LIBS=("$VKD3D/libvkd3d-shader.a" -lm -lpthread)

# Matches the size-relevant parts of crosire's own MSVC Release settings.
SIZE_FLAGS=(-Os -fno-exceptions -ffunction-sections -fdata-sections -s -Wl,--gc-sections)
# vkd3d-linked tools: exceptions stay on, since vkd3d's C++ shim is not audited
# for -fno-exceptions.
VKD3D_FLAGS=(-O2 -s -w)

BUILT=()

# --- reshadefx_cli (upstream, unmodified) ----------------------------------

if [ "$WANT_CLI" -eq 1 ]; then
	echo "Building reshadefx_cli ..."
	# Upstream's DXBC backend needs D3DCompiler; stub it so the tool links and
	# --dxbc simply reports it is unavailable.
	cat > "$WORK_DIR/dxbc_stub.cpp" << 'EOF'
#include "effect_codegen.hpp"
reshadefx::codegen *reshadefx::create_codegen_dxbc(unsigned int, bool, bool, int)
{
	return nullptr;
}
EOF
	g++ -std=c++17 "${SIZE_FLAGS[@]}" "${INCLUDES[@]}" "${FX_SRC[@]}" "${CODEGEN_SRC[@]}" \
		"$R/tools/fxc.cpp" "$WORK_DIR/dxbc_stub.cpp" \
		-o "$OUT_DIR/reshadefx_cli"
	BUILT+=(reshadefx_cli)
fi

# --- reshadefx_cli_fixed (fxc-fix.py + vkd3d --dxbc) -----------------------

if [ "$WANT_CLI_FIXED" -eq 1 ]; then
	echo "Building reshadefx_cli_fixed ..."
	mkdir -p "$WORK_DIR/fixed/tools"
	cp "$R/tools/fxc.cpp" "$WORK_DIR/fixed/tools/fxc.cpp"
	python3 "$SCRIPT_DIR/tools/fxc-fix.py" "$WORK_DIR/fixed"
	g++ -std=c++17 "${VKD3D_FLAGS[@]}" "${INCLUDES[@]}" "${VKD3D_INCLUDES[@]}" \
		"${FX_SRC[@]}" "${CODEGEN_SRC[@]}" "$SCRIPT_DIR/cli/effect_codegen_dxbc_vkd3d.cpp" \
		"$WORK_DIR/fixed/tools/fxc.cpp" "${VKD3D_LIBS[@]}" \
		-o "$OUT_DIR/reshadefx_cli_fixed"
	BUILT+=(reshadefx_cli_fixed)
fi

# --- reshadefx_coverage ------------------------------------------------------

if [ "$WANT_COVERAGE" -eq 1 ]; then
	echo "Building reshadefx_coverage ..."
	g++ -std=c++17 "${VKD3D_FLAGS[@]}" -DRESHADEFX_VERSION_NUM=$VER_NUM \
		"${INCLUDES[@]}" "${VKD3D_INCLUDES[@]}" \
		"${FX_SRC[@]}" "${CODEGEN_SRC[@]}" "$SCRIPT_DIR/cli/effect_codegen_dxbc_vkd3d.cpp" \
		"$SCRIPT_DIR/cli/coverage.cpp" "${VKD3D_LIBS[@]}" \
		-o "$OUT_DIR/reshadefx_coverage"
	BUILT+=(reshadefx_coverage)
fi

# --- reshadefx_rga -----------------------------------------------------------

if [ "$WANT_RGA" -eq 1 ]; then
	echo "Building reshadefx_rga ..."
	# SPIRV-Tools is linked rather than shelled out to, so the pass list and the
	# SPIRV-Tools version are pinned into the binary.
	SPIRV_TOOLS_FLAGS=()
	if [ "$HAVE_SPIRV_TOOLS" -eq 1 ]; then
		SPIRV_TOOLS_FLAGS=(-DRESHADEFX_HAVE_SPIRV_TOOLS
		                   ${SPIRV_TOOLS_INCLUDE_DIR:+-I"$SPIRV_TOOLS_INCLUDE_DIR"}
		                   -lSPIRV-Tools-opt -lSPIRV-Tools)
		echo "  SPIRV-Tools found: --optimize will be available"
	else
		echo "  SPIRV-Tools not found: --optimize will report it is unavailable"
		echo "  (Debian/Ubuntu: apt-get install spirv-tools)"
	fi
	g++ -std=c++17 "${SIZE_FLAGS[@]}" -DRESHADEFX_VERSION_NUM=$VER_NUM "${INCLUDES[@]}" \
		"${FX_SRC[@]}" "$R/source/effect_codegen_spirv.cpp" \
		"$SCRIPT_DIR/rga/reshadefx_rga.cpp" "$SCRIPT_DIR/rga/spirv_optimize.cpp" \
		"${SPIRV_TOOLS_FLAGS[@]}" \
		-o "$OUT_DIR/reshadefx_rga"
	BUILT+=(reshadefx_rga)
fi

# --- fxstat ------------------------------------------------------------------

if [ "$WANT_FXSTAT" -eq 1 ]; then
	echo "Building fxstat ..."
	cmake -S "$SCRIPT_DIR/fxstat" -B "$WORK_DIR/fxstat-build" -DCMAKE_BUILD_TYPE=Release \
		-DRESHADE_DIR="$R" -DSPIRV_HEADERS_DIR="$R/deps/spirv" \
		-DVKD3D_BUILD="$VKD3D" -DRESHADEFX_VERSION_NUM=$VER_NUM > /dev/null
	cmake --build "$WORK_DIR/fxstat-build" --parallel > /dev/null
	cp "$WORK_DIR/fxstat-build/fxstat" "$OUT_DIR/fxstat"
	BUILT+=(fxstat)
fi

echo
echo "Done (ReShade $RESHADE_REF). Built into $OUT_DIR:"
for b in "${BUILT[@]}"; do echo "  $b"; done
