@echo off
setlocal enabledelayedexpansion
REM Builds reshadefx_cli.exe and reshadefx_rga.exe from crosire/reshade's
REM real, unmodified compiler source, using MinGW-w64.
REM
REM Unlike the Linux/macOS build, reshadefx_cli.exe here also supports
REM --dxbc (real DX9/10/11/12-equivalent shader-model compilation via the
REM actual Microsoft D3DCompiler, since d3dcompiler_47.dll ships with
REM Windows itself) alongside --hlsl/--glsl/--spirv.
REM
REM Requires: git, and a MinGW-w64 g++ (x86_64) on PATH.
REM   Easiest install: https://winlibs.com (download, unzip, add its bin\ to PATH)
REM   or via MSYS2: pacman -S mingw-w64-x86_64-gcc
REM
REM Usage: build_reshadefx_tools.bat [output_dir] [--cli] [--rga]
REM
REM By default (no --cli/--rga given), both are built. Pass either flag to
REM build only one - e.g. if you only care about compile-correctness
REM checking for a project like ShaderBridge and have no use for the
REM optimization-focused rga tool:
REM   build_reshadefx_tools.bat --cli

set "RESHADE_COMMIT=358c345ca2fe64f86e67c694f8379c356627adcb"
set "SCRIPT_DIR=%~dp0"
if exist "%SCRIPT_DIR%RESHADE_VERSION" (
	set /p RESHADE_COMMIT=<"%SCRIPT_DIR%RESHADE_VERSION"
)

set "OUT_DIR="
set "WANT_CLI=0"
set "WANT_RGA=0"
set "ANY_SELECTED=0"

:parse_args
if "%~1"=="" goto args_done
if /I "%~1"=="--cli" (
	set "WANT_CLI=1"
	set "ANY_SELECTED=1"
	shift
	goto parse_args
)
if /I "%~1"=="--rga" (
	set "WANT_RGA=1"
	set "ANY_SELECTED=1"
	shift
	goto parse_args
)
set "OUT_DIR=%~1"
shift
goto parse_args
:args_done

if "%ANY_SELECTED%"=="0" (
	set "WANT_CLI=1"
	set "WANT_RGA=1"
)
if "%OUT_DIR%"=="" set "OUT_DIR=%SCRIPT_DIR%bin"
set "WORK_DIR=%TEMP%\reshadefx_build_%RANDOM%"

where g++ >nul 2>nul
if errorlevel 1 (
	echo ERROR: g++ not found on PATH. Install MinGW-w64 ^(e.g. from winlibs.com^) first.
	exit /b 1
)
where git >nul 2>nul
if errorlevel 1 (
	echo ERROR: git not found on PATH.
	exit /b 1
)

echo Fetching reshade @ %RESHADE_COMMIT% ...
git clone --quiet https://github.com/crosire/reshade.git "%WORK_DIR%\reshade"
if errorlevel 1 exit /b 1
pushd "%WORK_DIR%\reshade"
git checkout --quiet %RESHADE_COMMIT%
if errorlevel 1 exit /b 1
popd

echo Fetching SPIR-V headers ...
git clone --quiet --depth 1 https://github.com/KhronosGroup/SPIRV-Headers.git "%WORK_DIR%\reshade\deps\spirv"
if errorlevel 1 exit /b 1

REM Parse "vMAJOR.MINOR.REV" from RESHADE_COMMIT for --version text; falls
REM back to 0.0.0 if it's a raw commit hash instead (no dots to split on).
set "VERSTR=%RESHADE_COMMIT%"
if "%VERSTR:~0,1%"=="v" set "VERSTR=%VERSTR:~1%"
set "VER_MAJOR="
set "VER_MINOR="
set "VER_REV="
for /f "tokens=1,2,3 delims=." %%a in ("%VERSTR%") do (
	set "VER_MAJOR=%%a"
	set "VER_MINOR=%%b"
	set "VER_REV=%%c"
)
if "%VER_MINOR%"=="" set "VER_MAJOR=0"
if "%VER_MINOR%"=="" set "VER_REV=0"
if "%VER_MINOR%"=="" set "VER_MINOR=0"
set /a "VER_NUM=VER_MAJOR*10000 + VER_MINOR*100 + VER_REV"

REM res/version.h is normally generated by the Visual Studio build; only
REM used here for --version text and a preprocessor macro.
if not exist "%WORK_DIR%\reshade\res" mkdir "%WORK_DIR%\reshade\res"
set "VH=%WORK_DIR%\reshade\res\version.h"
echo #pragma once > "%VH%"
echo #define VERSION_MAJOR %VER_MAJOR% >> "%VH%"
echo #define VERSION_MINOR %VER_MINOR% >> "%VH%"
echo #define VERSION_REVISION %VER_REV% >> "%VH%"
echo #define VERSION_STRING_PRODUCT "ReShade %VER_MAJOR%.%VER_MINOR%.%VER_REV% (mingw-built reshadefx tools)" >> "%VH%"

REM Note: DXBC codegen (crosire's own effect_codegen_dxbc.cpp, unmodified) IS
REM built below for reshadefx_cli.exe - unlike the Linux/macOS build, this one
REM actually runs on Windows, where d3dcompiler_47.dll ships as part of the OS
REM itself. That gets --dxbc backed by the real Microsoft compiler, not an
REM approximation - no stubbing needed, no DLL to bundle.

if not exist "%OUT_DIR%" mkdir "%OUT_DIR%"
for %%I in ("%OUT_DIR%") do set "OUT_DIR=%%~fI"
REM ^ resolve to an absolute path now, before pushd changes the working directory
pushd "%WORK_DIR%\reshade"

set "INCLUDES=-I source -I res -I deps\spirv\include\spirv\unified1"
set "COMMON_SRC=source\effect_lexer.cpp source\effect_preprocessor.cpp source\effect_parser_exp.cpp source\effect_parser_stmt.cpp source\effect_symbol_table.cpp source\effect_expression.cpp"

REM Matches the size-relevant settings from crosire's own Release|x64 build
REM of ReShadeFXC.vcxproj (FunctionLevelLinking+OptimizeReferences ->
REM -ffunction-sections/-fdata-sections+--gc-sections; ExceptionHandling=false
REM -> -fno-exceptions, safe because reshadefx itself never throws/catches -
REM the only "try"/"catch" in its source are lexer keyword-table strings and
REM comments; GenerateDebugInformation=false -> -s to strip symbols). -Os
REM trades a little runtime speed for size, which doesn't matter for a
REM short-lived CLI compile tool. -static stays - unlike MSVC's /MT release
REM CRT, that one's there so the .exe needs no MinGW runtime DLLs at all.
set "SIZE_FLAGS=-Os -fno-exceptions -ffunction-sections -fdata-sections -s"
set "SIZE_LINK_FLAGS=-Wl,--gc-sections"

REM share.h provides SH_DENYWR, which MSVC headers define but MinGW's
REM equivalent lives in a separate header the source doesn't include.
if "%WANT_CLI%"=="1" (
	echo Building reshadefx_cli.exe ...
	g++ -std=c++17 %SIZE_FLAGS% -static -include share.h %INCLUDES% ^
		%COMMON_SRC% source\effect_codegen_hlsl.cpp source\effect_codegen_glsl.cpp source\effect_codegen_spirv.cpp source\effect_codegen_dxbc.cpp ^
		tools\fxc.cpp %SIZE_LINK_FLAGS% -ld3dcompiler ^
		-o "%OUT_DIR%\reshadefx_cli.exe"
	if errorlevel 1 exit /b 1
)

if "%WANT_RGA%"=="1" (
	echo Building reshadefx_rga.exe ...
	g++ -std=c++17 %SIZE_FLAGS% -DRESHADEFX_VERSION_NUM=%VER_NUM% -static -include share.h %INCLUDES% ^
		%COMMON_SRC% source\effect_codegen_spirv.cpp ^
		"%SCRIPT_DIR%reshadefx_rga.cpp" %SIZE_LINK_FLAGS% ^
		-o "%OUT_DIR%\reshadefx_rga.exe"
	if errorlevel 1 exit /b 1
)

popd
rmdir /s /q "%WORK_DIR%"

echo Done. Binaries in %OUT_DIR%
if "%WANT_CLI%"=="1" echo Example: %OUT_DIR%\reshadefx_cli.exe --hlsl -I path\to\reshade-shaders\Shaders -Fo out.hlsl myshader.fx
if "%WANT_CLI%"=="1" echo Example: %OUT_DIR%\reshadefx_cli.exe --dxbc --shader-model 50 -I path\to\reshade-shaders\Shaders -E MyEntryPoint -Fo out.cso myshader.fx
if "%WANT_RGA%"=="1" echo Example: %OUT_DIR%\reshadefx_rga.exe -I path\to\reshade-shaders\Shaders --rga path\to\rga.exe --asic gfx1100 myshader.fx
