#!/usr/bin/env bash
# Builds two Linux CLI tools from crosire/reshade's real, unmodified
# reshadefx compiler source (lexer, preprocessor, parser, symbol table,
# HLSL/GLSL/SPIR-V codegen). No Wine, no Windows dependency.
#
#   reshadefx_cli   - drop-in equivalent of the ReShadeFXC tool:
#                      compile a .fx file, report real compiler errors.
#   reshadefx_stats - compiles a .fx file and reports real SPIR-V
#                      instruction counts per shader entry point, for
#                      before/after optimization comparisons.
#
# Only the DXBC/DXIL backends are excluded (they call into Microsoft's
# D3DCompiler and are Windows-only). They are not needed to validate a
# port: HLSL/GLSL/SPIR-V codegen already proves the shader is valid.
#
# Usage: ./build_reshadefx_tools.sh [output_dir]
set -euo pipefail

RESHADE_COMMIT="358c345ca2fe64f86e67c694f8379c356627adcb"  # fallback if RESHADE_VERSION is absent
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
if [ -f "$SCRIPT_DIR/RESHADE_VERSION" ]; then
	RESHADE_COMMIT="$(tr -d '[:space:]' < "$SCRIPT_DIR/RESHADE_VERSION")"
fi
OUT_DIR="${1:-$SCRIPT_DIR/bin}"
WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

echo "Fetching reshade @ $RESHADE_COMMIT ..."
git clone --quiet https://github.com/crosire/reshade.git "$WORK_DIR/reshade"
git -C "$WORK_DIR/reshade" checkout --quiet "$RESHADE_COMMIT"

echo "Fetching SPIR-V headers ..."
git clone --quiet --depth 1 https://github.com/KhronosGroup/SPIRV-Headers.git "$WORK_DIR/reshade/deps/spirv"

# res/version.h is normally generated by the Visual Studio build; it is
# only used here for --version text and a preprocessor macro.
mkdir -p "$WORK_DIR/reshade/res"
VER_NUMS="$(echo "$RESHADE_COMMIT" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' || echo "0.0.0")"
VER_MAJOR="$(echo "$VER_NUMS" | cut -d. -f1)"
VER_MINOR="$(echo "$VER_NUMS" | cut -d. -f2)"
VER_REV="$(echo "$VER_NUMS" | cut -d. -f3)"
cat > "$WORK_DIR/reshade/res/version.h" << EOF
#pragma once
#define VERSION_MAJOR $VER_MAJOR
#define VERSION_MINOR $VER_MINOR
#define VERSION_REVISION $VER_REV
#define VERSION_STRING_PRODUCT "ReShade $VER_MAJOR.$VER_MINOR.$VER_REV (linux-built reshadefx tools)"
EOF

# Stub out the DXBC backend so the CLI tool still links; --dxbc simply
# is not available in this build.
cat > "$WORK_DIR/dxbc_stub.cpp" << 'EOF'
#include "effect_codegen.hpp"
reshadefx::codegen *reshadefx::create_codegen_dxbc(unsigned int, bool, bool, int)
{
	return nullptr;
}
EOF

mkdir -p "$OUT_DIR"
OUT_DIR="$(cd "$OUT_DIR" && pwd)"  # resolve to absolute before the cd below changes CWD
cd "$WORK_DIR/reshade"

COMMON_SRC=(
	source/effect_lexer.cpp
	source/effect_preprocessor.cpp
	source/effect_parser_exp.cpp
	source/effect_parser_stmt.cpp
	source/effect_symbol_table.cpp
	source/effect_expression.cpp
	source/effect_codegen_hlsl.cpp
	source/effect_codegen_glsl.cpp
	source/effect_codegen_spirv.cpp
)
INCLUDES=(-I source -I res -I deps/spirv/include/spirv/unified1)

echo "Building reshadefx_cli ..."
g++ -std=c++17 -O2 "${INCLUDES[@]}" "${COMMON_SRC[@]}" \
	tools/fxc.cpp "$WORK_DIR/dxbc_stub.cpp" \
	-o "$OUT_DIR/reshadefx_cli"

echo "Building reshadefx_stats ..."
g++ -std=c++17 -O2 "${INCLUDES[@]}" \
	source/effect_lexer.cpp source/effect_preprocessor.cpp \
	source/effect_parser_exp.cpp source/effect_parser_stmt.cpp \
	source/effect_symbol_table.cpp source/effect_expression.cpp \
	source/effect_codegen_spirv.cpp \
	"$SCRIPT_DIR/reshadefx_stats.cpp" \
	-o "$OUT_DIR/reshadefx_stats"

echo "Building reshadefx_rga ..."
g++ -std=c++17 -O2 "${INCLUDES[@]}" \
	source/effect_lexer.cpp source/effect_preprocessor.cpp \
	source/effect_parser_exp.cpp source/effect_parser_stmt.cpp \
	source/effect_symbol_table.cpp source/effect_expression.cpp \
	source/effect_codegen_spirv.cpp \
	"$SCRIPT_DIR/reshadefx_rga.cpp" \
	-o "$OUT_DIR/reshadefx_rga"

echo "Done. Binaries in $OUT_DIR"
echo "Example: $OUT_DIR/reshadefx_cli --hlsl -I path/to/reshade-shaders/Shaders -Fo out.hlsl myshader.fx"
echo "Example: $OUT_DIR/reshadefx_stats -I path/to/reshade-shaders/Shaders myshader.fx"
echo "Example: $OUT_DIR/reshadefx_rga -I path/to/reshade-shaders/Shaders myshader.fx"
echo "Example: $OUT_DIR/reshadefx_rga -I path/to/reshade-shaders/Shaders --rga /path/to/rga --asic gfx1100 myshader.fx"
