#!/usr/bin/env python3
"""
Generate the SPIR-V opcode -> (name, category) table from the Khronos grammar.

Categorisation is by explicit rule, in priority order, so it can be audited and
changed in one place rather than buried in a 400-case switch.

usage: gen_opcode_table.py <spirv.core.grammar.json> <out.cpp>
"""
import json
import sys

# (category, predicate) in priority order. First match wins.
# `n` is the opcode name, e.g. "OpImageSampleImplicitLod".
RULES = [
    # --- declarations: not instructions in a function body at all ---
    ("DECL", lambda n: n.startswith(("OpType", "OpConstant", "OpSpecConstant",
                                     "OpDecorate", "OpMemberDecorate", "OpDecoration",
                                     "OpGroupDecorate", "OpGroupMemberDecorate",
                                     "OpName", "OpMemberName", "OpString", "OpSource",
                                     "OpLine", "OpNoLine", "OpModuleProcessed",
                                     "OpCapability", "OpExtension", "OpExtInstImport",
                                     "OpMemoryModel", "OpEntryPoint", "OpExecutionMode"))),
    ("DECL", lambda n: n in ("OpUndef", "OpNop")),

    # --- texture / image access ---
    # OpImageTexelPointer is address computation for atomics, not a fetch.
    ("MEM", lambda n: n == "OpImageTexelPointer"),
    # OpSampledImage just pairs a texture with a sampler; free on all hardware.
    ("MOV", lambda n: n in ("OpSampledImage", "OpImage")),
    ("TEX", lambda n: n.startswith("OpImage")),

    # --- control flow ---
    ("FLOW", lambda n: n in (
        "OpBranch", "OpBranchConditional", "OpSwitch", "OpLoopMerge",
        "OpSelectionMerge", "OpLabel", "OpPhi", "OpKill", "OpReturn",
        "OpReturnValue", "OpUnreachable", "OpFunctionCall", "OpTerminateInvocation",
        "OpDemoteToHelperInvocation", "OpDemoteToHelperInvocationEXT",
        "OpLifetimeStart", "OpLifetimeStop", "OpTerminateRayKHR", "OpIgnoreIntersectionKHR")),

    # --- memory ---
    ("MEM", lambda n: n in (
        "OpLoad", "OpStore", "OpCopyMemory", "OpCopyMemorySized", "OpAccessChain",
        "OpInBoundsAccessChain", "OpPtrAccessChain", "OpInBoundsPtrAccessChain",
        "OpArrayLength", "OpVariable", "OpGenericPtrMemSemantics",
        "OpPtrEqual", "OpPtrNotEqual", "OpPtrDiff")),
    ("MEM", lambda n: n.startswith("OpAtomic")),

    # --- moves / swizzles / composites ---
    ("MOV", lambda n: n in (
        "OpCompositeConstruct", "OpCompositeExtract", "OpCompositeInsert",
        "OpVectorShuffle", "OpVectorExtractDynamic", "OpVectorInsertDynamic",
        "OpCopyObject", "OpCopyLogical", "OpTranspose")),

    # --- arithmetic / logic / conversion / extended instructions ---
    ("ALU", lambda n: n == "OpExtInst"),
    ("ALU", lambda n: n.startswith((
        "OpConvert", "OpBitcast", "OpBitwise", "OpBitField", "OpBitCount",
        "OpBitReverse", "OpShift", "OpLogical", "OpSelect", "OpIsNan",
        "OpIsInf", "OpIsFinite", "OpIsNormal", "OpSignBitSet",
        "OpQuantizeToF16", "OpSatConvert", "OpDPd", "OpDPdx", "OpDPdy",
        "OpFwidth", "OpUCount", "OpSCount"))),
    ("ALU", lambda n: n in (
        "OpSNegate", "OpFNegate", "OpNot", "OpAny", "OpAll", "OpDot",
        "OpVectorTimesScalar", "OpMatrixTimesScalar", "OpVectorTimesMatrix",
        "OpMatrixTimesVector", "OpMatrixTimesMatrix", "OpOuterProduct",
        "OpIAddCarry", "OpISubBorrow", "OpUMulExtended", "OpSMulExtended")),
    # Binary arithmetic and comparisons: OpFAdd, OpIMul, OpULessThan, OpFOrdEqual, ...
    ("ALU", lambda n: n.startswith(("OpF", "OpI", "OpU", "OpS")) and not n.startswith((
        "OpFunction", "OpImage", "OpIn", "OpUn", "OpSource", "OpString",
        "OpSampled", "OpSelection", "OpSwitch", "OpSpec", "OpStore", "OpSubgroup"))),

    # --- structural ---
    ("OTHER", lambda n: n in ("OpFunction", "OpFunctionEnd", "OpFunctionParameter")),
]


def categorise(name):
    for cat, pred in RULES:
        try:
            if pred(name):
                return cat
        except Exception:
            pass
    return "OTHER"


def main():
    grammar_path, out_path = sys.argv[1], sys.argv[2]
    with open(grammar_path) as f:
        grammar = json.load(f)

    # opcode -> (name, category). Core grammar only; keep the first spelling of
    # any aliased opcode so the table stays deterministic.
    table = {}
    for inst in grammar["instructions"]:
        op = inst["opcode"]
        if op in table:
            continue
        table[op] = (inst["opname"], categorise(inst["opname"]))

    lines = [
        "// Generated by tools/gen_opcode_table.py -- do not edit.",
        '#include "spirv_stats.hpp"',
        "",
        "namespace {",
        "struct entry { uint16_t op; const char *name; int8_t cat; };",
        "// cat: -1 = declaration (not a body instruction)",
        "const entry k_table[] = {",
    ]
    cat_enum = {
        "TEX": "static_cast<int8_t>(fxstat::category::tex)",
        "ALU": "static_cast<int8_t>(fxstat::category::alu)",
        "MOV": "static_cast<int8_t>(fxstat::category::mov)",
        "MEM": "static_cast<int8_t>(fxstat::category::mem)",
        "FLOW": "static_cast<int8_t>(fxstat::category::flow)",
        "OTHER": "static_cast<int8_t>(fxstat::category::other)",
        "DECL": "-1",
    }
    for op in sorted(table):
        name, cat = table[op]
        lines.append(f'\t{{ {op}, "{name}", {cat_enum[cat]} }},')
    lines += [
        "};",
        "",
        "const entry *find(uint16_t op) {",
        "\tsize_t lo = 0, hi = sizeof(k_table) / sizeof(k_table[0]);",
        "\twhile (lo < hi) {",
        "\t\tconst size_t mid = (lo + hi) / 2;",
        "\t\tif (k_table[mid].op == op) return &k_table[mid];",
        "\t\tif (k_table[mid].op < op) lo = mid + 1; else hi = mid;",
        "\t}",
        "\treturn nullptr;",
        "}",
        "} // namespace",
        "",
        "bool fxstat::classify_opcode(uint16_t opcode, fxstat::category &out) {",
        "\tconst entry *e = find(opcode);",
        "\tif (e == nullptr) { out = fxstat::category::other; return true; }",
        "\tif (e->cat < 0) return false;",
        "\tout = static_cast<fxstat::category>(e->cat);",
        "\treturn true;",
        "}",
        "",
        "const char *fxstat::opcode_name(uint16_t opcode) {",
        "\tconst entry *e = find(opcode);",
        '\treturn e != nullptr ? e->name : "OpUnknown";',
        "}",
        "",
        "const char *fxstat::category_name(fxstat::category c) {",
        "\tswitch (c) {",
        '\tcase fxstat::category::tex:  return "TEX";',
        '\tcase fxstat::category::alu:  return "ALU";',
        '\tcase fxstat::category::mov:  return "MOV";',
        '\tcase fxstat::category::mem:  return "MEM";',
        '\tcase fxstat::category::flow: return "FLOW";',
        '\tdefault:                     return "OTHER";',
        "\t}",
        "}",
        "",
    ]
    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {out_path}: {len(table)} opcodes")


if __name__ == "__main__":
    main()
