#!/usr/bin/env bash
# Builds two Linux CLI tools from crosire/reshade's real, unmodified
# reshadefx compiler source (lexer, preprocessor, parser, symbol table,
# HLSL/GLSL/SPIR-V codegen). No Wine, no Windows dependency.
#
#   reshadefx_cli   - drop-in equivalent of the ReShadeFXC tool:
#                      compile a .fx file, report real compiler errors.
#   reshadefx_rga   - makes RGA (Radeon GPU Analyzer) understand ReShade
#                      FX shaders, for real GPU ISA / register analysis;
#                      its built-in SPIR-V instruction classification also
#                      covers before/after optimization comparisons without
#                      needing RGA itself.
#
# Only the DXBC/DXIL backends are excluded (they call into Microsoft's
# D3DCompiler and are Windows-only). They are not needed to validate a
# port: HLSL/GLSL/SPIR-V codegen already proves the shader is valid.
#
# Usage: ./build_reshadefx_tools.sh [output_dir] [--cli] [--rga]
#
# By default (no --cli/--rga given), both are built. Pass either flag to
# build only one - e.g. if you only care about compile-correctness checking
# for a project like ShaderBridge and have no use for the
# optimization-focused rga tool:
#   ./build_reshadefx_tools.sh --cli
set -euo pipefail

RESHADE_COMMIT="358c345ca2fe64f86e67c694f8379c356627adcb"  # fallback if RESHADE_VERSION is absent
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
if [ -f "$SCRIPT_DIR/RESHADE_VERSION" ]; then
	RESHADE_COMMIT="$(tr -d '[:space:]' < "$SCRIPT_DIR/RESHADE_VERSION")"
fi

OUT_DIR=""
WANT_CLI=0
WANT_RGA=0
ANY_SELECTED=0
while [ $# -gt 0 ]; do
	case "$1" in
		--cli)
			WANT_CLI=1; ANY_SELECTED=1; shift ;;
		--rga)
			WANT_RGA=1; ANY_SELECTED=1; shift ;;
		*)
			OUT_DIR="$1"; shift ;;
	esac
done
if [ "$ANY_SELECTED" -eq 0 ]; then
	WANT_CLI=1
	WANT_RGA=1
fi
OUT_DIR="${OUT_DIR:-$SCRIPT_DIR/bin}"

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

echo "Fetching reshade @ $RESHADE_COMMIT ..."
git clone --quiet https://github.com/crosire/reshade.git "$WORK_DIR/reshade"
git -C "$WORK_DIR/reshade" checkout --quiet "$RESHADE_COMMIT"

echo "Fetching SPIR-V headers ..."
git clone --quiet --depth 1 https://github.com/KhronosGroup/SPIRV-Headers.git "$WORK_DIR/reshade/deps/spirv"

# res/version.h is normally generated by the Visual Studio build; it is
# only used here for --version text and a preprocessor macro.
mkdir -p "$WORK_DIR/reshade/res"
VER_NUMS="$(echo "$RESHADE_COMMIT" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' || echo "0.0.0")"
VER_MAJOR="$(echo "$VER_NUMS" | cut -d. -f1)"
VER_MINOR="$(echo "$VER_NUMS" | cut -d. -f2)"
VER_REV="$(echo "$VER_NUMS" | cut -d. -f3)"
# 10#$X forces base-10 interpretation, in case a component ever has a leading
# zero (bash would otherwise try, and fail, to parse it as octal).
VER_NUM=$((10#$VER_MAJOR * 10000 + 10#$VER_MINOR * 100 + 10#$VER_REV))
cat > "$WORK_DIR/reshade/res/version.h" << EOF
#pragma once
#define VERSION_MAJOR $VER_MAJOR
#define VERSION_MINOR $VER_MINOR
#define VERSION_REVISION $VER_REV
#define VERSION_STRING_PRODUCT "ReShade $VER_MAJOR.$VER_MINOR.$VER_REV (linux-built reshadefx tools)"
EOF

# Stub out the DXBC backend so the CLI tool still links; --dxbc simply
# is not available in this build.
cat > "$WORK_DIR/dxbc_stub.cpp" << 'EOF'
#include "effect_codegen.hpp"
reshadefx::codegen *reshadefx::create_codegen_dxbc(unsigned int, bool, bool, int)
{
	return nullptr;
}
EOF

mkdir -p "$OUT_DIR"
OUT_DIR="$(cd "$OUT_DIR" && pwd)"  # resolve to absolute before the cd below changes CWD
cd "$WORK_DIR/reshade"

COMMON_SRC=(
	source/effect_lexer.cpp
	source/effect_preprocessor.cpp
	source/effect_parser_exp.cpp
	source/effect_parser_stmt.cpp
	source/effect_symbol_table.cpp
	source/effect_expression.cpp
	source/effect_codegen_hlsl.cpp
	source/effect_codegen_glsl.cpp
	source/effect_codegen_spirv.cpp
)
INCLUDES=(-I source -I res -I deps/spirv/include/spirv/unified1)

# Matches the size-relevant parts of crosire's own MSVC Release settings, as the
# Windows .bat already does. The .sh was missing these.
SIZE_FLAGS=(-Os -fno-exceptions -ffunction-sections -fdata-sections -s
            -Wl,--gc-sections)

# SPIRV-Tools is optional and enables reshadefx_rga --optimize. Linked rather
# than shelled out to, so the pass list and the SPIRV-Tools version are pinned
# into the binary.
SPIRV_TOOLS_FLAGS=()
if [ -f /usr/include/spirv-tools/optimizer.hpp ] || [ -n "${SPIRV_TOOLS_INCLUDE_DIR:-}" ]; then
	SPIRV_TOOLS_FLAGS=(-DRESHADEFX_HAVE_SPIRV_TOOLS
	                   ${SPIRV_TOOLS_INCLUDE_DIR:+-I"$SPIRV_TOOLS_INCLUDE_DIR"}
	                   "$SCRIPT_DIR/spirv_optimize.cpp"
	                   -lSPIRV-Tools-opt -lSPIRV-Tools)
	echo "SPIRV-Tools found: reshadefx_rga --optimize will be available"
else
	SPIRV_TOOLS_FLAGS=("$SCRIPT_DIR/spirv_optimize.cpp")
	echo "SPIRV-Tools not found: reshadefx_rga --optimize will report it is unavailable"
	echo "  (Debian/Ubuntu: apt-get install spirv-tools)"
fi

if [ "$WANT_CLI" -eq 1 ]; then
	echo "Building reshadefx_cli ..."
	g++ -std=c++17 "${SIZE_FLAGS[@]}" "${INCLUDES[@]}" "${COMMON_SRC[@]}" \
		tools/fxc.cpp "$WORK_DIR/dxbc_stub.cpp" \
		-o "$OUT_DIR/reshadefx_cli"
fi

if [ "$WANT_RGA" -eq 1 ]; then
	echo "Building reshadefx_rga ..."
	g++ -std=c++17 "${SIZE_FLAGS[@]}" -DRESHADEFX_VERSION_NUM=$VER_NUM "${INCLUDES[@]}" \
		source/effect_lexer.cpp source/effect_preprocessor.cpp \
		source/effect_parser_exp.cpp source/effect_parser_stmt.cpp \
		source/effect_symbol_table.cpp source/effect_expression.cpp \
		source/effect_codegen_spirv.cpp \
		"$SCRIPT_DIR/reshadefx_rga.cpp" "${SPIRV_TOOLS_FLAGS[@]}" \
		-o "$OUT_DIR/reshadefx_rga"
fi

echo "Done. Binaries in $OUT_DIR"
[ "$WANT_CLI" -eq 1 ] && echo "Example: $OUT_DIR/reshadefx_cli --hlsl -I path/to/reshade-shaders/Shaders -Fo out.hlsl myshader.fx"
if [ "$WANT_RGA" -eq 1 ]; then
	echo "Example: $OUT_DIR/reshadefx_rga -I path/to/reshade-shaders/Shaders myshader.fx"
	echo "Example: $OUT_DIR/reshadefx_rga -I path/to/reshade-shaders/Shaders --rga /path/to/rga --asic gfx1100 myshader.fx"
fi
