#!/usr/bin/env bash
#
# Build reshadefx_cli with a working --dxbc target on Linux.
#
# crosire's source/effect_codegen_dxbc.cpp calls D3DCompile(), so upstream's
# --dxbc only exists on Windows. This substitutes effect_codegen_dxbc_vkd3d.cpp,
# which provides the same create_codegen_dxbc() symbol on top of vkd3d-shader.
#
# Also applies tools/fxc-fix.py, without which reshadefx_cli rejects effects
# ReShade compiles fine and silently compiles the wrong branch of others.
#
# usage: build.sh [out dir]
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
OUT="${1:-$HERE/bin}"
WORK="${WORK:-$HERE/.build}"

RESHADE_REF="${RESHADE_REF:-v6.8.0}"

mkdir -p "$WORK" "$OUT"
OUT="$(cd "$OUT" && pwd)"

# --- 1. vkd3d-shader -------------------------------------------------------

if [ ! -f "$WORK/vkd3d/libvkd3d-shader.a" ]; then
	"$ROOT/tools/build-vkd3d-shader.sh" "$WORK/vkd3d"
fi
VKD3D="$WORK/vkd3d"

# --- 2. reshade ------------------------------------------------------------

if [ ! -d "$WORK/reshade/.git" ]; then
	echo "Fetching reshade $RESHADE_REF ..."
	rm -rf "$WORK/reshade"
	git clone --quiet --depth 1 --branch "$RESHADE_REF" \
		https://github.com/crosire/reshade.git "$WORK/reshade" 2>/dev/null ||
	git clone --quiet --depth 1 https://github.com/crosire/reshade.git "$WORK/reshade"
fi
R="$WORK/reshade"

if [ ! -f "$R/deps/spirv/include/spirv/unified1/spirv.hpp" ]; then
	echo "Fetching SPIR-V headers ..."
	rm -rf "$R/deps/spirv"
	mkdir -p "$R/deps"
	git clone --quiet --depth 1 https://github.com/KhronosGroup/SPIRV-Headers.git "$R/deps/spirv"
fi

# res/version.h is generated by the Visual Studio build; only used for --version.
mkdir -p "$R/res"
VER="$(echo "$RESHADE_REF" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' || echo '0.0.0')"
cat > "$R/res/version.h" <<EOF
#pragma once
#define VERSION_MAJOR $(echo "$VER" | cut -d. -f1)
#define VERSION_MINOR $(echo "$VER" | cut -d. -f2)
#define VERSION_REVISION $(echo "$VER" | cut -d. -f3)
#define VERSION_STRING_PRODUCT "ReShade $VER (linux, vkd3d dxbc)"
EOF

# --- 3. the fxc.cpp fixes --------------------------------------------------

python3 "$ROOT/tools/fxc-fix.py" "$R"

# --- 4. build --------------------------------------------------------------

COMMON=(
	"$R/source/effect_lexer.cpp"
	"$R/source/effect_preprocessor.cpp"
	"$R/source/effect_parser_exp.cpp"
	"$R/source/effect_parser_stmt.cpp"
	"$R/source/effect_symbol_table.cpp"
	"$R/source/effect_expression.cpp"
	"$R/source/effect_codegen_hlsl.cpp"
	"$R/source/effect_codegen_glsl.cpp"
	"$R/source/effect_codegen_spirv.cpp"
	"$HERE/effect_codegen_dxbc_vkd3d.cpp"
)
INCLUDES=(
	-I "$R/source" -I "$R/res" -I "$R/deps/spirv/include/spirv/unified1"
	-I "$VKD3D/wine-src/libs/vkd3d/include" -I "$VKD3D/shim"
)

echo "Building reshadefx_cli ..."
g++ -std=c++17 -O2 -w "${INCLUDES[@]}" "${COMMON[@]}" "$R/tools/fxc.cpp" \
	"$VKD3D/libvkd3d-shader.a" -lm -lpthread -o "$OUT/reshadefx_cli"

echo "Building coverage ..."
g++ -std=c++17 -O2 -w "${INCLUDES[@]}" "${COMMON[@]}" "$HERE/coverage.cpp" \
	"$VKD3D/libvkd3d-shader.a" -lm -lpthread -o "$OUT/reshadefx_coverage"

echo
echo "built: $OUT/reshadefx_cli"
echo "       $OUT/reshadefx_coverage"
echo
echo "try:   $OUT/reshadefx_cli --dxbc --shader-model 50 --list-entry-points \\"
echo "         -I <reshade-shaders>/Shaders <effect.fx>"
